version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8085:8085"
  app:
    build: .
    command: npm start
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/app