version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MySql:/var/lib/mysql
    networks:
      - mysql-compose-network

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    hostname: "rabbit1"
    environment:
    - RABBITMQ_USERNAME=myapp
    - RABBITMQ_PASSWORD=myapp
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq1"

  mongo:
    image: mongo
    ports:
    - "27017:27017"

  #adminer:
  # image: adminer
  #  ports:
  #    - 8080:8080
  #  networks:
  #    - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge